# Generated by Django 5.1 on 2024-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
