# Generated by Django 5.1 on 2024-08-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0003_property_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
