# Generated by Django 5.1 on 2024-08-13 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0004_user_email_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.ImageField(blank=True, upload_to="property_images/"),
        ),
    ]
