# Generated by Django 5.1 on 2024-08-14 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0006_alter_userprofile_user_alter_message_property_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["-id"]},
        ),
    ]
