# Generated by Django 5.1 on 2024-08-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0007_alter_property_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="renthub.userprofile",
            ),
        ),
    ]
