# Generated by Django 5.1 on 2024-08-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0009_alter_property_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.ImageField(upload_to="property_images/"),
        ),
    ]
