# Generated by Django 5.1 on 2024-08-16 16:27

import django.db.models.deletion
from django.db import migrations, models

def set_default_user_profile(apps, schema_editor):
    Property = apps.get_model("renthub", "Property")
    UserProfile = apps.get_model("renthub", "UserProfile")
    default_userprofile = UserProfile.object.first()
    Property.objects.filter(owner__isnull=True).update(owner=default_userprofile)
class Migration(migrations.Migration):

    dependencies = [
        ("renthub", "0010_alter_property_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="message",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="property_messages",
                to="renthub.property",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="renthub.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="renthub.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("condo", "Condo"),
                    ("studio", "Studio"),
                    ("others", "Others"),
                ],
                default="apartment",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reviews",
                to="renthub.userprofile",
            ),
        ),
    ]
